# Generated by Django 4.1.13 on 2024-03-25 10:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('Firstname', models.CharField(max_length=100)),
                ('Lastname', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(8, message='Password must be at least 8 characters long'), django.core.validators.RegexValidator(message='Password must contain at least one uppercase letter, one lowercase letter, one digit, and one special character', regex='^(?=.*[A-Z])(?=.*[a-z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]+$')])),
                ('Confirm_Password', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(8, message='Password must be at least 8 characters long'), django.core.validators.RegexValidator(message='Password must contain at least one uppercase letter, one lowercase letter, one digit, and one special character', regex='^(?=.*[A-Z])(?=.*[a-z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]+$')])),
                ('Created_On', models.DateTimeField(auto_now_add=True)),
                ('Updated_On', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'UserRegistration',
            },
        ),
        migrations.CreateModel(
            name='UserTodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task', models.CharField(max_length=250)),
                ('Description', models.CharField(blank=True, max_length=300, null=True)),
                ('DueDate', models.DateTimeField()),
                ('Status', models.CharField(max_length=100)),
                ('Created_On', models.DateTimeField(auto_now_add=True)),
                ('Updated_On', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.userregister')),
            ],
            options={
                'db_table': 'UserTodoLists',
            },
        ),
    ]
